fix ip leak and restart section for case minutes
Edu4rdSHL/tor-router pull request #12
Opened 2023-12-27 15:51 UTC by Extr3m4R4710

# Overview
## Fix iptables flaws
The iptables on line 56 allows traffic for processes belonging to Tor's UID, but when the subsequent rule on line 57 is reached, it allows all traffic that does not meet the above criteria, causing an IP leak to an unspecified web site. This problem can be seen in ipinfo.io.

Specifically, the code is as follows

```bash
iptables -A OUTPUT -m owner --uid-owner "$TOR_UID" -j ACCEPT
iptables -A OUTPUT -j ACCEPT
```
## Fix restart command
There was a bug in the restart command that prevented it from triggering `stop` and `start` correctly. To solve this problem, we have made the content of case independent as a function.

````bash
function startTR()
{
	if test -f "$RULES"; then
		echo "$RULES exists. Either delete it, or stop tor-router first.
		exit 1
	else
		iptables-save >$RULES
# ... Skip...

case "$1" in
start)
	startTR
	;;
stop)
	stopTR
	;;
restart)
	restartTR
	;;
*)

```

2023-12-27 18:14 UTC, Extr3m4R4710 commented
#11

2023-12-27 22:12 UTC, Edu4rdSHL requested changes
Hey, thank you! Can you please check the small suggestion?

2023-12-27 22:12 UTC, Edu4rdSHL commented on files/tor-router
> +			iptables -A OUTPUT -j REJECT # ACCEPTから変更
Can we use pure English here?

2023-12-28 07:32 UTC, Edu4rdSHL commented
I tested it and once applied I can't ping or resolve anything.

2023-12-28 10:13 UTC, Extr3m4R4710 commented on files/tor-router
> +			iptables -A OUTPUT -j REJECT # ACCEPTから変更
Feel free to delete the comment. Looks like the comment for checking got pushed

2023-12-28 10:15 UTC, Extr3m4R4710 commented on files/tor-router
> +			iptables -A OUTPUT -j REJECT # ACCEPTから変更
I can read English, but I am not good at writing. But deepl solves everything.

2024-01-02 18:53 UTC, Extr3m4R4710 commented
Perhaps you can change `NON_TOR="192.168.1.0/24 192.168.0.0/24"` to `"192.168.0.0/16 172.16.0.0/12 10.0.0.0.0/8"` to send a ping. This is a verbatim transcription of an idea from Anonsurf, it well be sending ping

2024-01-05 08:15 UTC, closed without merging